# ---------------- Panel Server ----------------

[[servers]]
name = "panel"
listen = "0.0.0.0:8000"
https = false

[[servers.apis]]
path = "/"
target = "http://192.168.125.50"
replace_html_links = false
include_tail = true
payload_limit = 16777216 # 16MB

# ---------------- Web Socket Server ----------------

[[servers]]
name = "websocket"
listen = "0.0.0.0:12351"
https = false

[[servers.apis]]
path = "/"
target = "ws://192.168.125.50:12351"
replace_html_links = false
include_tail = true
payload_limit = 16777216 # 16MB
