[[servers]]
name = "test"
listen = "0.0.0.0:8080"
https = false

[[servers.apis]]
path = "/api/sum"
target = "http://80.253.141.222:10888"
target_path = "/sum"
payload_limit = 128
mode = "rule"

[[servers.apis.rules]]
field = ""
min_array_length = 2
max_array_length = 5
min = 1
max = 10

[[servers.apis]]
path = "/google"
target = "https://www.google.com"
target_path = "/"
mode = "raw"

[[servers.apis]]
path = "/zoomg"
target = "https://www.zoomg.ir"
# target_prefix = "/"
target_path = "/"
mode = "raw"
decompress = true

[[servers.apis]]
path = "/zoomg/{tail}"
target = "https://www.zoomg.ir"
replace_links = false
target_prefix = "/"
# target_path = "/"
mode = "raw"
decompress = false   

